# Dependencies
markdown:         redcarpet
pygments:         true
gems: ["emoji_for_jekyll", "jekyll-compass"]

# Permalinks
permalink:        pretty

# Setup
title:            Alex Stephen
tagline:          The Jekyll Butler
description:      Base theme for Jekyll themes by @mdo.
url:              http://getpoole.com

author:
  name:           Mark Otto
  url:            https://twitter.com/mdo

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
