# Jekyll General
permalink: /posts/:title/
name: Alex Stephen
url: https://rambleraptor.github.io
description: It's a blog!
future: true
google_analytics_tracking_id: UA-47334320-2

# SEO Social
twitter:
  username: rambleraptor
author:
  twitter: rambleraptor
