# Jekyll General
permalink: /posts/:title/
name: Alex Stephen
url: https://www.alexstephen.me
description: It's a blog!
future: true
google_analytics_tracking_id: 
gems:
  - jekyll-seo-tag

# SEO Social
twitter:
  username: rambleraptor
author:
  twitter: rambleraptor
