# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Alex Stephen
tagline:          My blog
description:      Technology and life from Alex Stephen
url:              http://alexstephen.me

author:
  name:           Alex Stephen
  url:            https://alexstephen.me

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://www.github.com/astephen2/astephen2.github.io

post:
  template:       _post_template.md
  extension:      markdown 
