# Jekyll General
permalink: /posts/:title/
name: Alex Stephen
url: http://www.alexstephen.me
description: It's a blog!
future: true
google_analytics_tracking_id: UA-38317192-1
gems:
  - jekyll-seo-tag

# SEO Social
twitter:
  username: rambleraptor
author:
  twitter: rambleraptor
google_site_verification: MQ6y9QHBxaBRek0-TDa-SxZJmh0NTThuIlEgdlfTKwo
